### ISSUE TITLE
errors on python3.12

### ISSUE THREAD

**Issue by matte22ladde** [tpet/mat2#7]
```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/mat2", line 14, in <module>
    from libmat2 import parser_factory, UNSUPPORTED_EXTENSIONS
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/libmat2/parser_factory.py", line 34, in <module>
    __load_all_parsers()
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/libmat2/parser_factory.py", line 31, in __load_all_parsers
    importlib.import_module('.' + name, package='libmat2')
  File "/data/data/com.termux/files/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/libmat2/images.py", line 7, in <module>
    import gi
  File "/data/data/com.termux/files/usr/lib/python3.12/site-packages/gi/__init__.py", line 40, in <module>
    from . import _gi
ImportError: dlopen failed: cannot locate symbol "PyType_Type" referenced by "/data/data/com.termux/files/usr/lib/python3.12/site-packages/gi/_gi.cpython-312.so"...
```

**Comment by lentrey** [comment]
Late to the party, i know, but i stumbled on this problem myself. You probably have a newer version of python, and mat2 creates a "/usr/lib/python<i>x.xx</i>" directory according to the version of python it was built with, while your system's python looks in its current version directory; just "cp -r /data/data/com.termux/files/usr/lib/python3.12/site-packages/libmat2  /data/data/com.termux/files/usr/lib/python<i>x.xx</i>/site-packages/" (do not forget to substitute python<i>x.xx</i> with your current version of python), and it should work
